name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.3'
      SERVERPOD_PASSWORD_database: 'NOsa1UtNFYUNhAzogkgCQvo4t_5ocrax'
      SERVERPOD_PASSWORD_redis: 'SPSArzeBChMxeDr94K7OAWH9i7H2lGP5'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: masterfabric_serverpod_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: masterfabric_serverpod_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: masterfabric_serverpod_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: masterfabric_serverpod_server
        run: serverpod generate

      - name: Run tests
        working-directory: masterfabric_serverpod_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: masterfabric_serverpod_server
        run: docker compose down -v
